### ISSUE TITLE
An issue when running your code

### ISSUE THREAD

**Issue by XiangEricHuangU** [hassiweb/otfs-chan-est-and-eq#1]
Hi,

I am very happy to find your code. But when I want to reproduce your results by running your code, one issue happened.  The hChannelCoder.decoder outputs the whole decoded code, so its dimension will not meet with txBits's dimension. Besides, the BLERs of all SNRs are 1.00 when I run this code. I think that's because of the decoder problem. Can you fix it? Thanks.

best,
Xiang

P.S. I use MATLAB 2019 to run your code on WINDOWS. I don't know if my problem comes from a different platform.

**Comment by hassiweb** [comment]
Hi Xiang,

Thank you for having an interest in my research.  
Unfortunately, I no longer have an environment to reproduce the issue.

Would you please let me know the vector (or matrix) sizes of `bitSeqA`, `bitSeqB`, `bitSeqC`, `bitSeqD`, `bitSeqE`, and `bitSeqF` in [function `decode` of class `LteChannelCoder`](https://github.com/hassiweb/otfs-chan-est-and-eq/blob/6fc82058cacdb87efa754e217546eebf2c0edafc/OTFS.m#L119) to understand the issue?

Also, would you please try [`channelCoding = 'None'`](https://github.com/hassiweb/otfs-chan-est-and-eq/blob/6fc82058cacdb87efa754e217546eebf2c0edafc/OTFS.m#L85) as the first step?  With this option, you can run the code without the LTE channel coding.  `LteChannelCoder` is too much for this simulation to do channel coding.  `LteChannelCoder` also composes of an unsupported function (specifically function `getf1f2`) in the latest MATLAB version.  It would be best if you implemented a much simpler channel coding for research purposes.

Thanks and regards,
Nori

**Comment by hassiweb** [comment]
No respones for a long time.  Let me close this issue.

**Comment by rajnigupta-555** [comment]
> Hi Xiang,
> 
> Thank you for having an interest in my research. Unfortunately, I no longer have an environment to reproduce the issue.
> 
> Would you please let me know the vector (or matrix) sizes of `bitSeqA`, `bitSeqB`, `bitSeqC`, `bitSeqD`, `bitSeqE`, and `bitSeqF` in [function `decode` of class `LteChannelCoder`](https://github.com/hassiweb/otfs-chan-est-and-eq/blob/6fc82058cacdb87efa754e217546eebf2c0edafc/OTFS.m#L119) to understand the issue?
> 
> Also, would you please try [`channelCoding = 'None'`](https://github.com/hassiweb/otfs-chan-est-and-eq/blob/6fc82058cacdb87efa754e217546eebf2c0edafc/OTFS.m#L85) as the first step? With this option, you can run the code without the LTE channel coding. `LteChannelCoder` is too much for this simulation to do channel coding. `LteChannelCoder` also composes of an unsupported function (specifically function `getf1f2`) in the latest MATLAB version. It would be best if you implemented a much simpler channel coding for research purposes.
> 
> Thanks and regards, Nori

I have using none still I am getting another error
Unable to resolve the name 'hChannelCoder.encode'.

Error in OFDM (line 226)
        txCodedBits = hChannelCoder.encode(txBits);
May I remove all the coding part
