### ISSUE TITLE
What do these parameters mean when performing Wiener deconvolution?

### ISSUE THREAD

**Issue by l291351760** [hassiweb/otfs-chan-est-and-eq#2]
if not(isempty(denominator(denominator<threshold)))
                            Pt = sqrt(M*N)*0.9472; % for 16QAM
                            Pr = mean(abs(Ydd_dft(:)));
                            Ph = (Pr - noiseVar*sqrt(M*N));
                            Ph_est = mean(abs(Hdd_dft(:)));
                            est_err = (Ph_est*Pt - Ph)/sqrt(M*N)/2;
                            denominator = denominator + est_err;
                        end
What do Pt, Pr, Ph and Ph_est stand for?
Hope you can tell me, thank you

**Comment by l291351760** [comment]
Implore brothers to inform

**Comment by hassiweb** [comment]
Hi,

Thank you for asking me.

`Pt`, `Pr`, `Ph` and `Ph_est` are the transmission power, received power, channel gain, and estimated channel gain, respectively.
As my paper doesn't state this calculation in detail (only the following footnote), it might not be an optimal method to conduct the best solution, and it isn't practical.
Please tackle it if you are interested in.

> Note: If channel estimation error exists in Λl
, the Wiener
 deconvolution can be empirically adjusted by two following
 options. The noise variance term in (22) can be considered an
 adjustable empirical parameter chosen to balance sharpness
 against noise [11]. Alternatively, the denominator of (22)
 should be modified locally to avoid zero division or division
 by a small value when high SNR [12].

Thanks and regards,

**Comment by l291351760** [comment]
Thank you for answering, thank you very much

**Comment by xpp237** [comment]
May I ask if you could provide me with a detailed introduction to the specific calculation principles of signal power, noise power, and gain? Why can they be expressed and calculated in this way? How does the coefficient root MN come from? Thank you very much

**Comment by l291351760** [comment]
Sorry, I don't understand the detailed principle, I directly follow the ideas of the big guys.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hassiweb/otfs-chan-est-and-eq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月7日(星期三) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hassiweb/otfs-chan-est-and-eq] What do these parameters mean when performing Wiener deconvolution? (Issue #2)





 
May I ask if you could provide me with a detailed introduction to the specific calculation principles of signal power, noise power, and gain? Why can they be expressed and calculated in this way? How does the coefficient root MN come from? Thank you very much

**Comment by xpp237** [comment]
can you find "I. Pitas, Digital Image Processing Algorithms and Applications. USA:
John Wiley & Sons, Inc., 1st ed., 2000."for help?THKS

**Comment by hassiweb** [comment]
Hi @xpp237, `Hdd_dft` and `Ydd_dft` are not power-normalized after applying `fft2`.  This is why you need to take into account this gain in these calculations.

**Comment by xpp237** [comment]
Thank you very much for your guidance. I now understand why it is necessary to calculate the modulus mean of Hdd-d ft and Ydd-d ft because power normalization has not been performed.
As I am very interested in this algorithm, there are a few points that I am not sure about during the running process:
(1) Is Pt=sqrt (MN) * 0.9472 for 16QAM an approximate power estimation since power normalization has already been achieved during the transmission signal constellation mapping process? If QPSK constellation modulation is used, what should it be;
(2) Does noiseVar * sqrt (MN) represent noise power; Why not noiseVar * sqrt (MN) * 2;
(3) Estimation error: est_ err, why divide by the coefficient sqrt (MN) * 2
Thank you again for your response

**Comment by xpp237** [comment]
what's the physical meaning of taking the modulus length of elements in a complex signal matrix and then calculating the mean, that is: (mean (abs (:)),please tell me details or refference resource
