### ISSUE TITLE
regarding error in running the code

### ISSUE THREAD

**Issue by rajnigupta-555** [hassiweb/otfs-chan-est-and-eq#3]
Sir kindly help in this regard
getf1f2' is used in Parallel Concatenated Convolutional Coding: Turbo Codes.

Error in LteChannelCoder (line 88)
                [f1, f2] = getf1f2(Kplus); % defined in TS36.212 section 5.1.3.2.3 Table 5.1.3-3

Error in OTFS (line 119)
        hChannelCoder = LteChannelCoder(

**Comment by hassiweb** [comment]
Please see my previous comment:
https://github.com/hassiweb/otfs-chan-est-and-eq/issues/1#issuecomment-947686609

Also, the following repository provides getf1f2 function:
https://github.com/shaohua0720/otfs-chan-est-and-eq

**Comment by hassiweb** [comment]
Let me close this issue due to no respone for a long time.
