### ISSUE TITLE
About the algorithm 1 in the paper.

### ISSUE THREAD

**Issue by Gao2000** [hassiweb/otfs-chan-est-and-eq#4]
You had written about the reason why using the stopping criteria.
But I am confused about the "if " in the repeat loop.
Why stop when finding the current path has a higher gain than the last?
![image](https://user-images.githubusercontent.com/43801144/172874936-2a76acc8-a311-47dd-b584-ab541946c1f2.png)

**Comment by hassiweb** [comment]
This algorithm estimates in the order of the largest path.
If an estimated path gain is higher than the previous estimated path gain, it means that the previous estimation is not perfect and makes an estimation error or the remaining paths that has not estimated is small enough.  If you don't stop the estimation here, the algorithm never stop.

If $\Upsilon(x)$ is orthogonal, there would be much better and optional algorithm.

**Comment by Gao2000** [comment]
When the condition occurred, the previous estimation probably had an error. Which may cause the following doppler will be wrong, so we need to jump to the next delay.

**Comment by hassiweb** [comment]
You are right.
