### ISSUE TITLE
NMSE

### ISSUE THREAD

**Issue by HDKjoe** [hassiweb/otfs-chan-est-and-eq#5]
Hello sir, do you have the code for evaluating the normalized mean square error (NMSE) according to your paper?

**Comment by HDKjoe** [comment]
![K`_~C3X) IVZO%XQD`5`61I](https://user-images.githubusercontent.com/109993839/180885382-cc936848-f198-4a66-b7b9-0498465bae6a.png)
![5}1~WW)4SA{I MSMC~9}1P2](https://user-images.githubusercontent.com/109993839/180885398-3ee1630a-df1d-428d-b655-bd3db6d6626c.png)

Is it necessary to calculate the channel matrix in the DD domain (\phi) through the estimated channel gain hp by equation(15)?
What is the forward cyclic shifted permutation matrix according to delay l here in equation(11)?

**Comment by hassiweb** [comment]
> Hello sir, do you have the code for evaluating the normalized mean square error (NMSE) according to your paper?

No.  Actually, it was done after I left the company where I had been doing this research.

**Comment by hassiweb** [comment]
> Is it necessary to calculate the channel matrix in the DD domain (\phi) through the estimated channel gain hp by equation(15)?

No.  An important thing for this algorithm is to estimate the effective channel matrix in the DD domain ($\Lambda$).

**Comment by hassiweb** [comment]
> What is the forward cyclic shifted permutation matrix according to delay l here in equation(11)?

It's the delay components from the CP.

**Comment by hassiweb** [comment]
No comment for a long time.  Let close this issue.
