### ISSUE TITLE
Question about updating delay and Doppler parameters

### ISSUE THREAD

**Issue by zhiha** [hassiweb/otfs-chan-est-and-eq#7]
```
  % The FDF is not a causal filter, especially if the delay is less than 1.
  
  % In this case, the FDF cannot keep the energy of an input signal such as a discontinuous signal (e.g., delta function).
  
  % To keep the same energy between discontinuous signals and continous signals, operations below convert parameters to express fractional delays.
  
  this.pathOrigRayleighGains = this.pathRayleighGains;
  
  this.pathOrigDopplers = this.pathDopplers;
  
  [this.pathRayleighGains, this.pathDopplers, this.pathDelays, this.pathOffsets] = fdfpathpars(this.pathRayleighGains, this.pathDopplers, this.delayProfile, this.pathOffsets, this.SamplingRate);
  
  this.pathDelaysInSample = this.pathDelays*this.SamplingRate;
```

Why update the path parameters through the fractional filter, I see that the number of paths has increased after the update, can the basis of the operation here provide some reference? ^_^

**Comment by hassiweb** [comment]
Hi @zhiha,
It is because the input paths are the fractional delay paths in the delay grid that is defined by the sampling rate.  There was no way to treat the fractional delayed paths.  Therefore, I introduced this process.
Thanks.

**Comment by zhiha** [comment]
Thank you for answering ^_^, So is it possible to understand so, for example, there were originally 9 fractional paths, this coefficient is adjusted through fd, given to the channel function, and the final effect is the signal superposition of these 9 fractional paths, that is, these 9 path coefficients are adjusted by fd, if the adjustment becomes 43 paths, these 43 paths are eventually equivalent to the theoretical effect of 9 paths.

**Comment by hassiweb** [comment]
Yes, that's what I did in this function.  There is a good reference for the FDF theory in the reference section in my paper.   Please check it out in detail.

**Comment by zhiha** [comment]
thx~ ^_^
